import type { ColorCollection } from './types'

/* Tier 3 semantic color, transcribed from DESIGN.md sections 2 to 5.

   Values are transcribed faithfully, including the ones DESIGN.md itself flags
   as broken. A hub that quietly "fixes" a token diverges from Figma and stops
   being a reference, so the fix is a loud warning on the token, not a
   different hex. */

export const colorCollections: ColorCollection[] = [
  {
    figma: 'Typography/Color',
    title: 'Text',
    intro:
      'Nine tokens. text/placeholder is the only one identical across modes — deliberately, since it sits mid-ramp and reads as a placeholder on both.',
    tokens: [
      {
        figma: 'text/primary',
        name: 'text-primary',
        light: '#1D2939',
        dark: '#FFFFFF',
        lightRamp: 'gray-blue-900',
        darkRamp: 'white',
        use: 'Headings and body. Maximum contrast for essential content.',
        utility: 'text-text-primary',
      },
      {
        figma: 'text/secondary',
        name: 'text-secondary',
        light: '#475467',
        dark: '#EAECF0',
        lightRamp: 'gray-blue-700',
        darkRamp: 'gray-blue-300',
        use: 'Labels and subtitles. Reduced emphasis, still legible.',
        utility: 'text-text-secondary',
      },
      {
        figma: 'text/tertiary',
        name: 'text-tertiary',
        light: '#667085',
        dark: '#D0D5DD',
        lightRamp: 'gray-blue-600',
        darkRamp: 'gray-blue-400',
        use: 'Captions, helper text, metadata.',
        utility: 'text-text-tertiary',
        gap: {
          severity: 'warning',
          note: 'Passes at 4.85:1 on surface/page but has almost no headroom. Do not use below 14px.',
        },
      },
      {
        figma: 'text/placeholder',
        name: 'text-placeholder',
        light: '#98A2B3',
        dark: '#98A2B3',
        lightRamp: 'gray-blue-500',
        darkRamp: 'gray-blue-500',
        use: 'Form placeholders, pre-input only.',
        utility: 'placeholder:text-text-placeholder',
      },
      {
        figma: 'text/disabled',
        name: 'text-disabled',
        light: '#D0D5DD',
        dark: '#475467',
        lightRamp: 'gray-blue-400',
        darkRamp: 'gray-blue-700',
        use: 'Non-interactive. The low contrast is intentional.',
        utility: 'text-text-disabled',
      },
      {
        figma: 'text/inverse',
        name: 'text-inverse',
        light: '#FFFFFF',
        dark: '#101828',
        lightRamp: 'white',
        darkRamp: 'gray-blue-950',
        use: 'Text on surfaces inverted from the page.',
        utility: 'text-text-inverse',
      },
      {
        figma: 'text/on-brand',
        name: 'text-on-brand',
        light: '#FFFFFF',
        dark: '#FFFFFF',
        lightRamp: 'white',
        darkRamp: 'white',
        use: 'Text on brand-colored surfaces. Always white.',
        utility: 'text-text-on-brand',
        gap: {
          severity: 'blocking',
          note: 'Fails on surface/brand in both modes (3.02 Light, 4.05 Dark). White on pink-500 does not reach 4.5:1.',
        },
      },
      {
        figma: 'text/link',
        name: 'text-link',
        light: '#6643CE',
        dark: '#A68AFA',
        lightRamp: 'purple-600',
        darkRamp: 'purple-300',
        use: 'Hyperlinks and interactive text.',
        utility: 'text-text-link',
      },
      {
        figma: 'text/link-hover',
        name: 'text-link-hover',
        light: '#5135A5',
        dark: '#BCA7FB',
        lightRamp: 'purple-700',
        darkRamp: 'purple-200',
        use: 'Link hover and pressed.',
        utility: 'hover:text-text-link-hover',
      },
    ],
  },
  {
    figma: 'Surface/Color',
    title: 'Surface',
    intro:
      'Ten tokens. The card family carries the file’s most serious open problem: its Light mode holds dark neutrals, which reads as the Dark ramp having landed in the Light column.',
    tokens: [
      {
        figma: 'surface/page',
        name: 'surface-page',
        light: '#FCFCFD',
        dark: '#08051A',
        lightRamp: 'gray-blue-50',
        darkRamp: 'indigo-950',
        use: 'App background. Sets the tone of the screen.',
        utility: 'bg-surface-page',
      },
      {
        figma: 'surface/subtle',
        name: 'surface-subtle',
        light: '#F9FAFB',
        dark: '#1D2939',
        lightRamp: 'gray-blue-100',
        darkRamp: 'gray-blue-900',
        use: 'Sections, alternating rows, grouping areas.',
        utility: 'bg-surface-subtle',
      },
      {
        figma: 'surface/card',
        name: 'surface-card',
        light: '#344054',
        dark: '#2C2B5B',
        lightRamp: 'gray-blue-800',
        darkRamp: 'lavender-800',
        use: 'Default card. Dark is anchored on Lavender-800 as an optical adjustment — brand personality without saturating the UI.',
        utility: 'bg-surface-card',
        gap: {
          severity: 'blocking',
          note: 'Light mode is unshipped. text/primary on this card measures 1.41:1. Do not build Light-mode cards until this is resolved.',
        },
      },
      {
        figma: 'surface/card-raised',
        name: 'surface-card-raised',
        light: '#475467',
        dark: '#1D1D3D',
        lightRamp: 'gray-blue-700',
        darkRamp: 'lavender-900',
        use: 'Elevated or emphasized card. One step from card.',
        utility: 'bg-surface-card-raised',
        gap: { severity: 'blocking', note: 'Light mode is unshipped — see surface/card.' },
      },
      {
        figma: 'surface/card-sunken',
        name: 'surface-card-sunken',
        light: '#1D2939',
        dark: '#121125',
        lightRamp: 'gray-blue-900',
        darkRamp: 'lavender-950',
        use: 'Lower-hierarchy card, nested inside a primary card.',
        utility: 'bg-surface-card-sunken',
        gap: {
          severity: 'blocking',
          note: 'Light mode is unshipped, and shares #1D2939 with overlay and inverse — three intents, no differentiation.',
        },
      },
      {
        figma: 'surface/overlay',
        name: 'surface-overlay',
        light: '#1D2939',
        dark: '#2C2B5B',
        lightRamp: 'gray-blue-900',
        darkRamp: 'lavender-800',
        use: 'Modals, drawers, sheets, tooltips.',
        utility: 'bg-surface-overlay',
        gap: {
          severity: 'blocking',
          note: 'Light mode is unshipped, and shares #1D2939 with card-sunken and inverse.',
        },
      },
      {
        figma: 'surface/disabled',
        name: 'surface-disabled',
        light: '#F2F4F7',
        dark: '#344054',
        lightRamp: 'gray-blue-200',
        darkRamp: 'gray-blue-800',
        use: 'Disabled element backgrounds.',
        utility: 'bg-surface-disabled',
      },
      {
        figma: 'surface/inverse',
        name: 'surface-inverse',
        light: '#1D2939',
        dark: '#FCFCFD',
        lightRamp: 'gray-blue-900',
        darkRamp: 'gray-blue-50',
        use: 'Toasts, snackbars, text tooltips.',
        utility: 'bg-surface-inverse',
      },
      {
        figma: 'surface/brand',
        name: 'surface-brand',
        light: '#FF5A70',
        dark: '#DE485D',
        lightRamp: 'pink-500',
        darkRamp: 'pink-600',
        use: 'CTAs, banners, brand headers.',
        utility: 'bg-surface-brand',
        gap: {
          severity: 'blocking',
          note: 'text/on-brand fails on this surface in both modes. Also: the Figma description says Purple while the token resolves to Pink.',
        },
      },
      {
        figma: 'surface/brand-subtle',
        name: 'surface-brand-subtle',
        light: '#DE485D',
        dark: '#AA3C4B',
        lightRamp: 'pink-600',
        darkRamp: 'pink-700',
        use: 'Tags, badges, brand highlights.',
        utility: 'bg-surface-brand-subtle',
        gap: {
          severity: 'warning',
          note: 'Inverted: it resolves darker than surface/brand itself. The description calls for a very soft tint — it should sit at pink-50/100.',
        },
      },
    ],
  },
  {
    figma: 'Border/Color',
    title: 'Border',
    intro:
      'Ten tokens. Feedback borders invert direction across modes — 600 in Light, 400 in Dark. Keep that pattern for any new feedback token.',
    tokens: [
      {
        figma: 'border/default',
        name: 'border-default',
        light: '#D0D5DD',
        dark: '#7472C3',
        lightRamp: 'gray-blue-400',
        darkRamp: 'lavender-400',
        use: 'Cards and containers. Dark sits four steps above surface/card for guaranteed chromatic harmony.',
        utility: 'border-border-default',
      },
      {
        figma: 'border/subtle',
        name: 'border-subtle',
        light: '#EAECF0',
        dark: '#3B397A',
        lightRamp: 'gray-blue-300',
        darkRamp: 'lavender-700',
        use: 'Dividers and internal separators.',
        utility: 'border-border-subtle',
      },
      {
        figma: 'border/strong',
        name: 'border-strong',
        light: '#98A2B3',
        dark: '#908ECF',
        lightRamp: 'gray-blue-500',
        darkRamp: 'lavender-300',
        use: 'Card hover, selected elements, emphasis.',
        utility: 'border-border-strong',
      },
      {
        figma: 'border/focus',
        name: 'border-focus',
        light: '#7A50F7',
        dark: '#906DF8',
        lightRamp: 'purple-500',
        darkRamp: 'purple-400',
        use: 'Accessible focus ring. Purple to separate it from every other border.',
        utility: 'focus-visible:border-border-focus',
      },
      {
        figma: 'border/disabled',
        name: 'border-disabled',
        light: '#EAECF0',
        dark: '#475467',
        lightRamp: 'gray-blue-300',
        darkRamp: 'gray-blue-700',
        use: 'Disabled elements.',
        utility: 'border-border-disabled',
      },
      {
        figma: 'border/error',
        name: 'border-error',
        light: '#F04438',
        dark: '#FDA29B',
        lightRamp: 'red-600',
        darkRamp: 'red-400',
        use: 'Failed validation.',
        utility: 'border-border-error',
      },
      {
        figma: 'border/success',
        name: 'border-success',
        light: '#12B76A',
        dark: '#6CE9A6',
        lightRamp: 'green-600',
        darkRamp: 'green-400',
        use: 'Confirmations.',
        utility: 'border-border-success',
      },
      {
        figma: 'border/warning',
        name: 'border-warning',
        light: '#F79009',
        dark: '#FEC84B',
        lightRamp: 'yellow-600',
        darkRamp: 'yellow-400',
        use: 'Alerts requiring attention.',
        utility: 'border-border-warning',
      },
      {
        figma: 'border/brand',
        name: 'border-brand',
        light: '#6643CE',
        dark: '#906DF8',
        lightRamp: 'purple-600',
        darkRamp: 'purple-400',
        use: 'Active brand elements: tags, chips, banners.',
        utility: 'border-border-brand',
      },
      {
        figma: 'border/inverse',
        name: 'border-inverse',
        light: '#F2F4F7',
        dark: '#344054',
        lightRamp: 'gray-blue-200',
        darkRamp: 'gray-blue-800',
        use: 'Borders on inverted surfaces.',
        utility: 'border-border-inverse',
      },
    ],
  },
  {
    figma: 'Accent/Color',
    title: 'Accent',
    intro:
      'Seven tokens. Decorative and categorical only — never the sole carrier of meaning, and never used for text on its own.',
    tokens: [
      {
        figma: 'accent/brand',
        name: 'accent-brand',
        light: '#FF5A70',
        dark: '#FF8C9C',
        lightRamp: 'pink-500',
        darkRamp: 'pink-400',
        use: 'Ontop’s historic brand color. Identity highlights and badges.',
        utility: 'bg-accent-brand',
      },
      {
        figma: 'accent/purple',
        name: 'accent-purple',
        light: '#7A50F7',
        dark: '#906DF8',
        lightRamp: 'purple-500',
        darkRamp: 'purple-400',
        use: 'Primary category. Avatars, decorative icons, tier badges.',
        utility: 'bg-accent-purple',
      },
      {
        figma: 'accent/lavender',
        name: 'accent-lavender',
        light: '#5856B7',
        dark: '#7472C3',
        lightRamp: 'lavender-500',
        darkRamp: 'lavender-400',
        use: 'Secondary category. Harmonic with surface/card.',
        utility: 'bg-accent-lavender',
      },
      {
        figma: 'accent/blue',
        name: 'accent-blue',
        light: '#528BFF',
        dark: '#84ADFF',
        lightRamp: 'blue-500',
        darkRamp: 'blue-400',
        use: 'Informational and neutral. Metrics, first chart series.',
        utility: 'bg-accent-blue',
      },
      {
        figma: 'accent/green',
        name: 'accent-green',
        light: '#32D583',
        dark: '#6CE9A6',
        lightRamp: 'green-500',
        darkRamp: 'green-400',
        use: 'Positive. Growth, completed payments, second series.',
        utility: 'bg-accent-green',
      },
      {
        figma: 'accent/yellow',
        name: 'accent-yellow',
        light: '#FDB022',
        dark: '#FEC84B',
        lightRamp: 'yellow-500',
        darkRamp: 'yellow-400',
        use: 'Attention and pending. In-progress states, third series.',
        utility: 'bg-accent-yellow',
      },
      {
        figma: 'accent/red',
        name: 'accent-red',
        light: '#F97066',
        dark: '#FDA29B',
        lightRamp: 'red-500',
        darkRamp: 'red-400',
        use: 'Negative. Rejections, payment failures, fourth series.',
        utility: 'bg-accent-red',
      },
    ],
  },
]

/** Fixed, so the same metric keeps the same color across surfaces. */
export const chartSeriesOrder = [
  'accent-blue',
  'accent-green',
  'accent-yellow',
  'accent-red',
  'accent-purple',
  'accent-lavender',
]
